# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_name', models.CharField(help_text='Name', max_length=30)),
                ('patient_ID', models.CharField(help_text='Patient ID', max_length=20, primary_key=True, serialize=False)),
                ('patient_age', models.CharField(help_text=' Age', max_length=5)),
                ('patient_issue', models.CharField(help_text='Issue', max_length=40)),
                ('other_details', models.CharField(help_text='Other Details', max_length=40)),
                ('patient_file', models.ImageField(upload_to='pictures/')),
            ],
        ),
    ]
