# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20180607_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_ID',
            field=models.CharField(help_text='Patient ID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
