# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
