# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0009_remove_patient_patient_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_file',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
